# INTRO

[[exercises]]
name = "intro1"
path = "exercises/intro/src/main.nr"
mode = "test"
hint = """
No hints this time ;)
"""

# MERKLE TREE

[[exercises]]
name = "merkle-tree"
path = "exercises/merkle-tree/src/main.nr"
mode = "test"
hint = """
No hints this time ;)
"""

# VARIABLES

[[exercises]]
name = "variables1"
path = "exercises/variables/variables1.nr"
mode = "compile"
hint = """
No hint this time
"""
