# INTRO

[[exercises]]
name = "intro1"
path = "exercises/intro/intro1.nr"
mode = "test"
hint = """
No hints this time ;)
"""

# MERKLE TREE

# [[exercises]]
# name = "merkle-tree"
# path = "exercises/merkle-tree/merkle.nr"
# mode = "test"
# hint = """
# No hints this time ;)
# """

# VARIABLES

[[exercises]]
name = "variables1"
path = "exercises/variables/variables1.nr"
mode = "compile"
hint = """
No hint this time
"""

[[exercises]]
name = "variables2"
path = "exercises/variables/variables2.nr"
mode = "compile"
hint = """
No hint this time
"""

[[exercises]]
name = "variables3"
path = "exercises/variables/variables3.nr"
mode = "compile"
hint = """
No hint this time
"""

[[exercises]]
name = "variables4"
path = "exercises/variables/variables4.nr"
mode = "compile"
hint = """
No hint this time
"""

[[exercises]]
name = "variables5"
path = "exercises/variables/variables5.nr"
mode = "compile"
hint = """
No hint this time
"""

[[exercises]]
name = "variables6"
path = "exercises/variables/variables6.nr"
mode = "compile"
hint = """
No hint this time
"""


# CONTROL FLOW

[[exercises]]
name = "if1"
path = "exercises/control-flow/if1.nr"
mode = "test"
hint = """
No hint this time
"""

[[exercises]]
name = "grade_calculator"
path = "exercises/control-flow/grade_calculator.nr"
mode = "test"
hint = """
No hint this time
"""


[[exercises]]
name = "count_factors"
path = "exercises/control-flow/count_factors.nr"
mode = "test"
hint = """
No hint this time
"""


# Arrays

[[exercises]]
name = "array_basics"
path = "exercises/arrays/array_basics.nr"
mode = "test"
hint = """
No hint this time
"""
